volumes:
  core_postgres_data:
  core_redis_data:

networks:
  default:

services:
  core-postgres:
    image: postgres:17.4-bookworm
    restart: always
    environment:
      POSTGRES_USER: core
      POSTGRES_PASSWORD: core
      POSTGRES_DB: core
    expose:
      - "5432"
    volumes:
      - core_postgres_data:/var/lib/postgresql/data
    networks:
      - default
    healthcheck:
      test: ["CMD", "pg_isready", "-q", "-d", "core", "-U", "core"]
      interval: 30s
      timeout: 10s
      retries: 5

  core-redis:
    image: redis:7.4.2-bookworm
    restart: always
    expose:
      - "6379"
    volumes:
      - core_redis_data:/data
    networks:
      - default
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 5

  core-api:
    image: ghcr.io/mairie360/core-api:latest
    pull_policy: always
    restart: always
    environment:
      BINDING_ADDRESS: "0.0.0.0"
      BINDING_PORT: 3000
      POSTGRES_URL: postgresql://core:core@core-postgres:5432/core
      REDIS_URL: redis://core-redis:6379
    expose:
      - "3000"
    networks:
      - default
    depends_on:
      core-postgres:
        condition: service_healthy
      core-redis:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://127.0.0.1:3000/health"]
      interval: 30s
      timeout: 10s
      retries: 5

  nginx:
    image: nginx:1.27.4-bookworm
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    networks:
      - default
    depends_on:
      core-api:
        condition: service_healthy