volumes:
  postgres-data:
  redis-data:

networks:
  default:

services:
  postgres:
    image: postgres:17.4-bookworm
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    expose:
      - "5432"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - postgres-data:/var/lib/postgresql/data
    networks:
      - default
    healthcheck:
      test: ["CMD", "pg_isready", "-q", "-d", "postgres", "-U", "postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7.4.2-bookworm
    restart: always
    expose:
      - "6379"
    volumes:
      - redis-data:/data
    networks:
      - default
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  core:
    image: ghcr.io/mairie360/core:latest
    pull_policy: always
    restart: always
    environment:
      HOSTNAME: "0.0.0.0"
      PORT: 3000
      POSTGRES_URL: postgresql://postgres:postgres@postgres:5432/core
      REDIS_URL: redis://redis:6379
    expose:
      - "3000"
    networks:
      - default
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://127.0.0.1:3000/api/health"]
      interval: 10s
      timeout: 5s
      retries: 5

  files:
    image: ghcr.io/mairie360/files:latest
    pull_policy: always
    restart: always
    environment:
      HOSTNAME: "0.0.0.0"
      PORT: 3000
      POSTGRES_URL: postgresql://postgres:postgres@postgres:5432/files
      REDIS_URL: redis://redis:6379
      CORE_PUBLIC_URL: http://localhost:3000
    expose:
      - "3000"
    networks:
      - default
    depends_on:
      core:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://127.0.0.1:3000/api/health"]
      interval: 10s
      timeout: 5s
      retries: 5

  calendars:
    image: ghcr.io/mairie360/calendars:latest
    pull_policy: always
    restart: always
    environment:
      HOSTNAME: "0.0.0.0"
      PORT: 3000
      POSTGRES_URL: postgresql://postgres:postgres@postgres:5432/calendars
      REDIS_URL: redis://redis:6379
      CORE_PUBLIC_URL: http://localhost:3000
    expose:
      - "3000"
    networks:
      - default
    depends_on:
      core:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://127.0.0.1:3000/api/health"]
      interval: 10s
      timeout: 5s
      retries: 5

  emails:
    image: ghcr.io/mairie360/emails:latest
    pull_policy: always
    restart: always
    environment:
      HOSTNAME: "0.0.0.0"
      PORT: 3000
      POSTGRES_URL: postgresql://postgres:postgres@postgres:5432/emails
      REDIS_URL: redis://redis:6379
      CORE_PUBLIC_URL: http://localhost:3000
    expose:
      - "3000"
    networks:
      - default
    depends_on:
      core:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://127.0.0.1:3000/api/health"]
      interval: 10s
      timeout: 5s
      retries: 5

  projects:
    image: ghcr.io/mairie360/projects:latest
    pull_policy: always
    restart: always
    environment:
      HOSTNAME: "0.0.0.0"
      PORT: 3000
      POSTGRES_URL: postgresql://postgres:postgres@postgres:5432/projects
      REDIS_URL: redis://redis:6379
      CORE_PUBLIC_URL: http://localhost:3000
    expose:
      - "3000"
    networks:
      - default
    depends_on:
      core:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://127.0.0.1:3000/api/health"]
      interval: 10s
      timeout: 5s
      retries: 5

  messages:
    image: ghcr.io/mairie360/messages:latest
    pull_policy: always
    restart: always
    environment:
      HOSTNAME: "0.0.0.0"
      PORT: 3000
      POSTGRES_URL: postgresql://postgres:postgres@postgres:5432/messages
      REDIS_URL: redis://redis:6379
      CORE_PUBLIC_URL: http://localhost:3000
    expose:
      - "3000"
    networks:
      - default
    depends_on:
      core:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://127.0.0.1:3000/api/health"]
      interval: 10s
      timeout: 5s
      retries: 5

  nginx:
    image: nginx:1.27.4-bookworm
    restart: always
    ports:
      - "3000:3000"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    networks:
      - default
    depends_on:
      files:
        condition: service_healthy
      calendars:
        condition: service_healthy
      emails:
        condition: service_healthy
      projects:
        condition: service_healthy
      messages:
        condition: service_healthy