CREATE DATABASE core;
CREATE DATABASE files;
CREATE DATABASE calendars;
CREATE DATABASE emails;
CREATE DATABASE projects;
CREATE DATABASE messages;

GRANT ALL PRIVILEGES ON DATABASE core TO postgres;
GRANT ALL PRIVILEGES ON DATABASE files TO postgres;
GRANT ALL PRIVILEGES ON DATABASE calendars TO postgres;
GRANT ALL PRIVILEGES ON DATABASE emails TO postgres;
GRANT ALL PRIVILEGES ON DATABASE projects TO postgres;
GRANT ALL PRIVILEGES ON DATABASE messages TO postgres;