name: Mirror

on:
  push:
    branches:
      - main

jobs:
  mirror:
    if: github.repository != 'EpitechPromo2027/G-EIP-600-RUN-6-1-eip-clement-antoine.xavier'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.2.2
        with:
          fetch-depth: 0

      - uses: yesolutions/mirror-action@v0.7.0
        with:
          REMOTE: 'git@github.com:EpitechPromo2027/G-EIP-600-RUN-6-1-eip-clement-antoine.xavier.git'
          GIT_SSH_PRIVATE_KEY: ${{ secrets.GIT_SSH_PRIVATE_KEY }}
          GIT_SSH_NO_VERIFY_HOST: "true"