name: Mirror

on:
  push:
    branches:
      - main

env:
  REPOSITORY: 'git@github.com:EpitechPromo2027/G-EIP-600-RUN-6-1-eip-clement-antoine.xavier.git'

jobs:
  mirror:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.2.2
        with:
          fetch-depth: 0
      - uses: yesolutions/mirror-action@v0.7.0
        with:
          REMOTE: $REPOSITORY
          BRANCH: main
          GIT_SSH_PRIVATE_KEY: ${{ secrets.GIT_SSH_PRIVATE_KEY }}
          GIT_SSH_KNOWN_HOSTS: ${{ secrets.GIT_SSH_KNOWN_HOSTS }}